# Generated by Django 5.2.6 on 2025-10-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_veiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.SmallIntegerField(choices=[(1, 'AUDI'), (2, 'BMW'), (3, 'CHEVROLET'), (4, 'FERRARI'), (5, 'FIAT'), (6, 'FORD'), (7, 'HONDA'), (8, 'HYUNDAI'), (9, 'VOLKSWAGEN'), (10, 'LAMBORGHINI')]),
        ),
    ]
