# Generated by Django 5.2.6 on 2025-10-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0004_veiculo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='usuario',
        ),
    ]
