# Generated by Django 5.2.7 on 2025-11-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'NIKE'), (2, 'ADIDAS'), (3, 'PUMA'), (4, 'REEBOK'), (5, 'NEW BALANCE'), (6, 'VANS'), (7, 'CONVERSE'), (8, 'ASICS'), (9, 'MIZUNO'), (10, 'OLYMPIKUS')])),
                ('modelo', models.CharField(max_length=100)),
                ('tamanho', models.IntegerField()),
                ('cor', models.SmallIntegerField(choices=[(1, 'VERMELHO'), (2, 'BRANCO'), (3, 'AZUL'), (4, 'PRETO'), (5, 'CINZA'), (6, 'AMARELO')])),
                ('tipo', models.SmallIntegerField(choices=[(1, 'CASUAL'), (2, 'ESPORTIVO'), (3, 'CORRIDA'), (4, 'SKATISTA')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='tenis/fotos')),
            ],
        ),
    ]
